name: Run linters and update the latest

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  check:
    name: "Test & Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Lint *.sh files
      run: |
        find . -name '*.sh' -exec shellcheck --color=always {} +

    - name: Update 'latest' tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git tag -f latest
        git push origin --force tag latest
