name: Build & Test library

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [blacksmith-2vcpu-ubuntu-2404]
        zig-version: [latest, master]
    steps:
    - uses: actions/checkout@v5

    # Install runtimes
    - uses: actions/setup-python@v6
      with: { python-version: '3.13' }
    - uses: actions/setup-node@v5
      with: { node-version: "latest" }
    - uses: mlugg/setup-zig@v2
      with: { version: "${{ matrix.zig-version }}" }

    - name: Install tools
      run: |
        pip install reuse==5.1.1
        npm install --global markdownlint-cli2@0.18.1

    # Static checks and linters
    - name: Check licenses
      run: reuse lint

    - name: Check markdown formatting
      run: markdownlint-cli2 "**/*.md"

    - name: Check zig formatting
      run: zig fmt --ast-check --check .

    # Library checks
    - name: Build
      run: zig build --summary all

    - name: Unit tests
      run: zig build test --summary all
