name: Look for issues in packages

on:
  push:
    branches: [ main ]
  schedule:
  - cron: 0 */3 * * * # every 3 hours
  workflow_dispatch:

permissions:
  contents: read

jobs:
  overseer:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm  # arm is half the price
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        activate-environment: true

    - name: Install tools
      run: |
        uv sync --locked --all-extras

    - run: python -m src.zigdevel inspect --github-token ${{ secrets.GITHUB_TOKEN }}
